format = "$directory $git_branch $git_status\n$character"

right_format = "$cmd_duration"

scan_timeout = 500
command_timeout = 60000

# add_newline = true

# [fill]
# symbol = ' '

[character]
format = "$symbol "

[directory]
truncation_length = 1
# truncate_to_repo = true
format = "[$path]($style)"

[time]
disabled = false
time_format = "%T"
format = "[$time]($style)"

[cmd_duration]
min_time = 3000
show_milliseconds = true
format = '(yellow)[$duration]($style)'

[git_branch]
format = "[$branch]($style)"
