
theme = "gruvbox_dark_hard"

[editor]
mouse = true  # 'true' to ensure scroll doesn't break the buffer
true-color = true
color-modes = true
# bufferline = "multiple"
line-number = "relative"
scroll-lines = 1
# breadcrumbs = true
cursorline = true
end-of-line-diagnostics = "hint"
rulers = [80, 100, 120]

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┆" # Some c haracters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = true
auto-signature-help = true
# goto-definition-marker-style = "underline"

[keys.normal]

"ñ" = "command_mode"
# "ret" = "goto_word"

# Line selection reverse operator
"A-x" = "select_line_above"

# Subwords motions
"W" = "move_next_sub_word_start"
"B" = "move_prev_sub_word_start"
"E" = "move_next_sub_word_end"

# Use 'esc' to unselect multiple cursors
"esc" = ["collapse_selection", "keep_primary_selection"]

# Move line up/down
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

# VSCode like select next ocurrence (Normal)
"C-d" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]

# Reload all files (maybe edited in other editor)
"C-r" = [":reload-all"]

# Opens git-ui
"C-g" = [
    ":write-all",
    ":insert-output gitui >/dev/tty",
    ":redraw",
    ":reload-all"
]

# Go next/prev paragraph
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

# Scooter for symbol rename (?)
# "C-r" = [
#     ":write-all",
#     ":insert-output scooter >/dev/tty",
#     ":redraw",
#     ":reload-all"
# ]

[keys.normal.space]

" " = "global_search"
"m" = "suspend"

# "w" = ":w"
"W" = ":wa"
"q" = ":q"
"x" = ":bc"

# Opens YAZI explorer
"tab" = [
  ":write-all",
  ":sh rm -f /tmp/helix_yazi_link",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/helix_yazi_link",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/helix_yazi_link}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]

[keys.select]

# Line selection reverse operator
"A-x" = "select_line_above"

# Subwords motions
"W" = 'extend_next_sub_word_start'
"B" = 'extend_prev_sub_word_start'
"E" = 'extend_next_sub_word_end'

# Move line up/down
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

# VSCode like select next ocurrence (Select)
"C-d" = ["search_selection", "extend_search_next"]

[keys.insert]

# Completion
"C-x" = "completion"

# Move line up/down
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

# VSCode like select next ocurrence (Insert)
"C-d" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]
